set_mode:
  fields:
    mode:
      required: true
      example: Sursemis
      selector:
        select:
          translation_key: gazon_mode
          options:
            - Normal
            - Sursemis
            - Traitement
            - Fertilisation
            - Biostimulant
            - Agent Mouillant
            - Scarification
            - Hivernage

set_date_action:
  fields:
    date_action:
      required: false
      example: "2026-03-12"
      selector:
        text:

reset_mode: {}

start_manual_irrigation:
  fields:
    objectif_mm:
      required: true
      example: 3
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: mm

start_auto_irrigation:
  fields:
    objectif_mm:
      required: false
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: mm

declare_intervention:
  fields:
    intervention:
      required: true
      selector:
        select:
          translation_key: gazon_intervention
          options:
            - Sursemis
            - Traitement
            - Fertilisation
            - Biostimulant
            - Agent Mouillant
            - Scarification
            - Hivernage
    date_action:
      required: false
      selector:
        text:

declare_mowing:
  fields:
    date_action:
      required: false
      selector:
        text:

declare_watering:
  fields:
    date_action:
      required: false
      selector:
        text:
    objectif_mm:
      required: false
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: mm
