[mypy]
python_version = 3.13
warn_unused_configs = True
ignore_missing_imports = True
follow_imports = silent
check_untyped_defs = True
files =
    custom_components/gazon_intelligent/config_flow.py,
    custom_components/gazon_intelligent/entity_ids.py,
    custom_components/gazon_intelligent/entity_migration.py,
    custom_components/gazon_intelligent/migration.py
